version: "3.9"
services:
  respotter:
    container_name: respotter
    image: ghcr.io/lawndoc/respotter:latest
    network_mode: host
    cap_add:
      - NET_RAW
    security_opt:
      - label:disable
    restart: always
    volumes:
      - ./config:/config
      - ./state:/state